#THIS FILE IS TO BE CALLED INTO VAIIYA_terminal.py AND USED AS A RETURN VALUE TYPE SETTINGS SYSTEM. 

#DEV

class DEV():

    def DEBUGMODE():
        # COMMENT OUT THE SETTING YOU DO NOT WANT, AND UNCOMMENT THE SETTING YOU DO WANT
        return True
        #return False